### ISSUE TITLE
Too much debug logging turned on

### ISSUE THREAD

**Issue by jacklovell** [D-TACQ/acq400_hapi#114]
The following line turns on debugging for all loggers:

https://github.com/D-TACQ/acq400_hapi/blob/963fae60af3be2e6159cda07c0bccd829647cd07/acq400_hapi/debug.py#L9

When other packages are used in a script along with `acq400_hapi`, any debug log messages from those packages get emitted as well, which can really clutter the output of the script.

It would be better to just configure the acq400_hapi.debug logger with debug logging:
```python
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
```

**Comment by petermilne** [comment]
DONE! Thank you very much!
