### ISSUE TITLE
missing colon

### ISSUE THREAD

**Issue by FilipJankyTE** [D-TACQ/acq400_hapi#119]
https://github.com/D-TACQ/acq400_hapi/blob/3ea4d03f28ee475a94d84024be376b0de90f29a9/user_apps/acq400/acq400_awg_load1.py#L23

**Comment by petermilne** [comment]
Fixed, thanks!
commit a522bd56dd577a8edae4d2dcf21c46c216030ac3 (HEAD -> master)
Author: Peter Milne <peter.milne@d-tacq.com>
Date:   Wed Jun 29 21:11:16 2022 +0100

    Fix python3 non-compliances
     On branch master
            modified:   user_apps/acq400/acq400_awg_load1.py
