### ISSUE TITLE
the links pointing to docs in README.md files do not work

### ISSUE THREAD

**Issue by FilipJankyTE** [D-TACQ/acq400_hapi#123]
The links in the README.md files are not found
e.g. acq400_hapi/user_apps/acq400/README.md https://d-tacq.github.io/acq400_hapi/html/user_apps/acq400/
e.g. acq400_hapi/acq400/README.md https://D-TACQ.github.io/acq400_hapi/html/acq400_hapi/index.html

I think other links might be also broken.

**Comment by petermilne** [comment]
github.io pages dissappeared ... so now the links must disappear as well
