### ISSUE TITLE
acq400_hapi is not python 3.7 ready

### ISSUE THREAD

**Issue by zack-vii** [D-TACQ/acq400_hapi#90]
Two issues so far that could be better.
testing for matplotlib should print the warning only when plotting is used.
Also the Exception is not necessary RuntimeError, e.g. on python 3.7 it is ModuleNotFoundError, best go with general Exception.

at some points its expecting future. before printing the warning it should check
```
if sys.version_info < (3,):
```
otherwise the future has arrived and does not need to be imported ;)

Currently testing it on 3.7 supporting the developing of the MDSplus pydevices. I will eventually file a PullRequest with solutions i found.

**Comment by petermilne** [comment]
Thanks zack-vii!: 
fixed with commit 7c4795f5f946f6e32e5f292c0813341d779a9867
